server:
  port: 9002
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/auth-service
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"