server:
  port: 9096
spring:
  application:
    name: Zuul-gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"