server:
  port: 9096
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: weather
          uri: lb://weather-service
          predicates:
            - Path=/weather/**
          filters:
            - JwtAuthenticationFilter
  aop:
    proxy-target-class: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoint:
    web:
      exposure:
        include: "*"