server:
  port: 9096
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/login, /auth/registration, /auth/guest-login, /auth/register
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: gateway-actuator
          uri: lb://gateway
          predicates:
            - Path=actuator/**
          filters:
            - JwtAuthenticationFilter
            - PrivilegeCheckFilter=actuator
        - id: weather-service-mirror
          uri: lb://weather-service
          predicates:
            - Path=/weather/mirror
          filters:
            - JwtAuthenticationFilter
            - PrivilegeCheckFilter=mirror
            - RewritePath=/weather/(?<segment>.*), /$\{segment}
        - id: weather-service-hello
          uri: lb://weather-service
          predicates:
            - Path=/weather/hello
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/weather/(?<segment>.*), /$\{segment}
        - id: weather-service-hello
          uri: lb://weather-service
          predicates:
            - Path=/weather/privilege
          filters:
            - JwtAuthenticationFilter
            - PrivilegeCheckFilter=privilege
            - RewritePath=/weather/(?<segment>.*), /$\{segment}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"