server:
  port: 9096
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-login
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: gateway-actuator
          uri: lb://gateway
          predicates:
            - Path=actuator/**
        - id: weather-service
          uri: lb://weather-service
          predicates:
            - Path=/weather/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/weather/(?<segment>.*), /$\{segment}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"